[package]
name = "keybinds"
version = "0.0.1"
edition = "2021"
authors = ["rhysd <lin90162@yahoo.co.jp>"]
description = "Platform&Framework-agnostic key bindings parser and matcher"
license = "MIT"
homepage = "https://github.com/rhysd/keybinds-rs#readme"
repository = "https://github.com/rhysd/keybinds-rs"
keywords = ["key", "bindings", "configuration", "shortcut", "keyboard"]
categories = ["config"]

[[example]]
name = "crossterm"
required-features = ["crossterm"]

[features]
default = []
serde = ["dep:serde"]
crossterm = ["dep:crossterm"]

[dependencies]
bitflags = "2.8.0"
crossterm = { version = "0.28.1", optional = true }
serde = { version = "1.0.217", optional = true }

[dev-dependencies]
toml = { version = "0.8.20", default-features = false, features = ["parse"] }
serde = { version = "1.0.217", features = ["derive"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
features = ["serde"]
rustdoc-args = ["--cfg", "docsrs"]
