[package]
name = "keybinds"
version = "0.0.3"
edition = "2021"
authors = ["rhysd <lin90162@yahoo.co.jp>"]
description = "Platform&Framework-agnostic key bindings parser and dispatcher"
license = "MIT"
homepage = "https://github.com/rhysd/keybinds-rs#readme"
repository = "https://github.com/rhysd/keybinds-rs"
keywords = ["key", "bindings", "configuration", "shortcut", "keyboard"]
categories = ["config"]
include = [
    "/src",
    "/examples",
    "/LICENSE.txt",
    "/README.md",
]

[[example]]
name = "crossterm"
required-features = ["crossterm"]

[[example]]
name = "termwiz"
required-features = ["termwiz"]

[[example]]
name = "winit"
required-features = ["winit"]

[features]
default = []
serde = ["dep:serde"]
crossterm = ["dep:crossterm"]
winit = ["dep:winit"]
termwiz = ["dep:termwiz"]

[dependencies]
bitflags = "2.8.0"
crossterm = { version = "0.28.1", optional = true }
serde = { version = "1.0.217", optional = true }
termwiz = { version = "0.23.0", optional = true }
winit = { version = "0.30.9", optional = true }

[dev-dependencies]
toml = { version = "0.8.20", default-features = false, features = ["parse"] }
serde = { version = "1.0.217", features = ["derive"] }

[workspace]
members = [".", "bench"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
features = ["serde", "crossterm", "winit", "termwiz"]
rustdoc-args = ["--cfg", "docsrs"]
