[package]
name = "keybinds"
version = "0.0.0"
edition = "2021"
authors = ["rhysd <lin90162@yahoo.co.jp>"]
description = "Platform-agnostic key bindings parser and matcher"
license = "MIT"
homepage = "https://github.com/rhysd/keybinds-rs#readme"
repository = "https://github.com/rhysd/keybinds-rs"
keywords = ["key", "bindings", "configuration", "shortcut", "keyboard"]
categories = ["config"]

[dependencies]
bitflags = "2.8.0"
serde = { version = "1.0.217", features = ["derive"] }

[dev-dependencies]
toml = { version = "0.8.20", default-features = false, features = ["parse"] }
